- name: Install pip3
  apt:
    name: python3-pip
    state: present
  become: true

- name: Install docker and docker-compose modules via pip3
  pip:
    name:
      - docker
      - docker-compose
    executable: pip3
  become: true

- name: Run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports:
      - "8084:8080"
    state: started
